### ISSUE TITLE
Refresh Token not populating

### ISSUE THREAD

**Issue by donovanmote** [bitfocus/companion-module-spotify-remote#79]
I realized I added to an issue that wasn't the same as the one I am experiencing. I had a working Spotify connection that stopped recognizing my active device. I recently upgraded the hard drive in that machine so I thought it might be related to that. The 'Write the ID of the current Active Device to config' function stopped working and eventually I deleted the connection and App from Spotify developer site, and started over. I follow all the instructions and previously successful steps but cannot get a refresh token to populate.

Thanks in advance for your guidance...

> Same. Deleted plugin and app, reinstalled plugin, new app, copied new client ID and Secret, inserted recommended redirect URL, received new approval code, inserted code in Approval Code field within Companion App but no refresh token gets populated. 

 _Originally posted by @donovanmote in [#78](https://github.com/bitfocus/companion-module-spotify-remote/issues/78#issuecomment-3076087204)_

**Comment by awbarker84** [comment]
I'm having this issue as well.   My working config failed.  I tried to refresh the auth which had worked before to no avail.  So i created a new app and started fresh.

I can generate a new auth code - but the access token and refresh token are not populating.

**Comment by donovanmote** [comment]
I fixed it! It turns out my Raspberry pi wasn't actually talking to the internet, which was super confusing considering I could connect to the companion web GUI from a computer on the same network that had internet connectivity. My clue was that none of the modules would update or populate. I figured out how to terminal into the Raspberry pi (I am a total novice to Linux) and tried to ping 8.8.8.8 with no success, but I pinged my modem/router with success. I realized that I set up the Raspberry pi at my office initially where the gateway is xxx.xxx.xxx.2, but its xxx.xxx.xxx.1 at my home office where I have been trying to build more functionality. I used the command sudo ip route add default via 192.168.1.1 And everything started working! Was able to generate a refresh token and update the active device ID for Spotify. Sweet Success... Hope this helps someone in the future.

**Comment by popeter1** [comment]
i am getting the same issue but can confim application can ping externally
log outputs a  Response code 400 (Bad Request)

**Comment by awbarker84** [comment]
i am still unable to generate an access token.  i can ping everything as described above.

**Comment by awbarker84** [comment]
i have resolved my connection issue.  while i could ping out to 8.8.8.8 and could access the companion admin from a separate computer, a vpn connection was running that was causing issues.  with the vpn turned off, the token was generated and function restored.
